# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: QA Deployment

on:
  push:
    branches: [ qa ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: sh ci-cd/install-dependencies.sh
      env:
        ARTIFACTORY_READER_PASSWORD: ${{ secrets.ARTIFACTORY_READER_PASSWORD }}
        ARTIFACTORY_READER_USER: ${{ secrets.ARTIFACTORY_READER_USER }}
    - run: npm run build
  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Restore cache
      uses: actions/cache@v2
      id: cache-app
      env:
        cache-name: angular-source
      with:
        path: src
        key: ${{ env.cache-name }}-${{ hashFiles('**/src/**','**/*.properties') }}-cache
    - name: Install dependencies
      run: sh ci-cd/install-dependencies.sh
      env:
        ARTIFACTORY_READER_PASSWORD: ${{ secrets.ARTIFACTORY_READER_PASSWORD }}
        ARTIFACTORY_READER_USER: ${{ secrets.ARTIFACTORY_READER_USER }}
    - run: npm test
    - run: npm run coverage
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: steps.cache-app.outputs.cache-hit != 'true'
  deploy:
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sh ci-cd/install-dependencies.sh
      env:
        ARTIFACTORY_READER_PASSWORD: ${{ secrets.ARTIFACTORY_READER_PASSWORD }}
        ARTIFACTORY_READER_USER: ${{ secrets.ARTIFACTORY_READER_USER }}
    - run: npm run build:qa
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: mn-demo-github-actions
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist/bbog-dig-angular-template-web-ui'