name: requirements-frontend
on:
  pull_request:
    branches:
      - qa
      - master
      - staging

jobs:
  requirements-frontend:
    uses: bancodebogota/bbog-dt-pipeline/.github/workflows/requirements_angular_frontend.yml@v2
    with:
      node-version: "16.x"
      test-command: "npm run test:coverage"
      sonar-project-properties-file: "sonar-project-custom.properties"
    secrets: inherit